### ISSUE TITLE
Basic Roadmap to MVP

### ISSUE THREAD

**Issue by sdhull** [sdhull/strategic_voting#1]
## High level features to be broken out & tackled individually:
- [x] Registration with email confirmation
  - [x] Should include state & desired candidate
- [x] allow users to be logged in without bein confirmed, but be excluded from matching pool
  - [x] show logged-in uncomfirmed users a page asking them to confirm their email with the option to resend the confirmation email
- [x] add public-facing `name` field to users
- [ ] chores
  - [x] emails need to send in the background (recommend sucker_punch)
  - [x] google analytics
  - [x] new relic
  - [x] rollbar
  - [x] about page
  - [x] legal verbage & tos?
  - [x] faq page
  - [ ] contact page (?)
  - [ ] contributor guide in readme
- [x] design / branding
- [x] share buttons everywhere
## Features for later iterations:
- [ ] Matching
  - examples:
  - If you're in an uncontested state (and you want to vote Hillary), we'd match you with someone in a contested state who wants to vote for Jill Stein
  - If you're in an uncontested state and you want to vote for Jill Stein, you'd be excluded from matching pool with a message like `"Right on! You won't be indirectly helping Drumpf!"`
  - if you're in a contested state and you want to vote for Hillary, you'd be excluded from the matching pool with a message like `"Right on! You're helping to defeat Drumpf!"`
  - If you register as wanting to vote for Drumpf, we render a page mocking you (or something else tbd)
  - [ ] states need smart prioritization. tbd what that means exactly.
  - [ ] matching should be delayed until we have good liquidity and some uncertainties have been resolved (eg, October-ish)
  - [ ] unless we can't find a match for them, in which case we tell them that we'll email them when we match them
  - [x] if a confirmed user returns while waiting for a match, we show them a waiting page
  - [ ] once matched, remove users from matching pool
  - [x] if a user comes back to the site after being matched, it simply shows them something like `"You've been matched with Bob! You will vote for so-and-so, and they will vote for such-and-such"` with a call to action to share on social media.
- Mobile number verification (for 2fa but also identity verification / preventing gaming the system)
- data viz

**Comment by sdhull** [comment]
So for state prioritization, it'd be nice to find a query-able source for state polls, so we could have live-updating state prioritization based on recent polls (without having to manually update poll data in the app)

**Comment by sdhull** [comment]
So this complicates the `state prioritization` item above (as brought up by irl):
http://www.jill2016.com/ballot_access
http://sourceplanet.net/politics/bernie-sanders-write-in-states-what-you-need-to-know/

Apparently write-in candidates are not allowed in many states, and in some states you can't write-in someone who lost the primary race in that state ("Sore Loser" laws).

**Comment by ishanraval** [comment]
Some scattered thoughts: 
1. Top priority states could be determined on an optimization of two factors: a) where Stein isn't on the ballot and has a very small chance on being on it (like North Carolina), and b) the most critical states (acc. to a July 15 post on FiveThirtyEight, Nate Silver said these are Florida, Pennsylvania and Ohio followed by Virginia and NC). These should be paired with strong red or blue states, where, respectively, Clinton has a negligible chance of winning anyway and where we're not realistically going to hurt her chances of winning by making voters there go to Stein.
2. As for the ballot access issue, I think we can use this to our advantage: The website can be made and publicized whenever possible, but we could state that we're not going to make matches till October. a) There will be greater clarity on the ballot access issue then, b) The greater the number of people that have signed up, the best we can match, so it could make sense to give it some time regardless, c) Polls will be more reliable at that point.
3. Just a rhetorical point, but "contested" and "uncontested" states isn't that common a term, and I can it being a few extra seconds of cognition that people would have to expend on comprehending that. Everyone understands "swing states", and as their counterpart, I came up with "sealed states." Or it could be swing states and uncontested states. Just that "swing states" being there will probably immediately get people to understand what you're talking about.
4. I think a very legitimizing and attractive component of this could be a sort of live projection factoring in the vote swaps, if it would be programmable/if we could find a good enough psephologist/general statistician. (A good friend of mine's one of those crazy prodigal math PhD student types, specializing in probability theory; I can ask him.)  As in, smack on the homepage, a little overview of what election results would look like if people followed through on their vote swaps. A comparison between the projections without the vote swaps, and how it would look with the vote swaps. And then, even more complex, if possible, making further matches based on our live projections, so that we know which states to most prioritize not based on these swap-unconsidering projections but smarter ones, so that if we're not overcompensating. Again, I have no coding skills, so I don't know whether this would be possible, but I do think seeing the actual results of their actions would go a long way in countering the effect of the voting irrationality paradox and pumping up people to participate.

**Comment by sdhull** [comment]
1. Good ideas on state prioritization, I like it
2. Point well taken. I agree with waiting till October to match users. Another great outcome of delaying the matching is we can delay building the specifics of state prioritization & matching, so we can get our first iteration live sooner. I've pushed "matching" into "later" section
3. Gotcha. I'll update verbiage throughout the code to reflect "swing" vs "uncontested" or "sealed"
4. Yeah good ideas for data visualization! I've added a generic "data viz" item in the "later" section.

**Comment by StevenGubkin** [comment]
You might also suggest some strategies for helping to ensure vote swapping compliance.

For instance, if you exchange FaceBook information with your mate, and then both publicly declare your intention to vote swap, you can see how their friends react to this (from "When did you start supporting Stein instead of Trump" to "Right on!  I am so glad you found a way not to contribute to Nader effect").  The public declaration also puts social pressure on both parties to follow through.

I am sure we could think of more.  Also worth reminding people that taking a picture of their vote is illegal, for good reasons.

**Comment by sdhull** [comment]
@StevenGubkin I like the idea around encouraging people to declare their support on FB, with a link back to the site, of course. 😉 

Are you absolutely certain that photographing your vote is illegal? Not very enforceable as long as it's kept relatively private, right?

**Comment by StevenGubkin** [comment]
@sdhull Apparently the legality varies from state to state.

Here is a state by state guide: http://www.huffingtonpost.com/2014/11/03/photo-polling-place_n_6095746.html

It is illegal for a good reason though.  Imagine if your employer said "Vote republican and take a picture or you will be fired from your job".  Secret voting eliminates this kind of thing.

Some other countries let you vote as many times as you like, and only the last vote counts.  This prevents these sort of attacks, because even if you are being compelled to vote a certain way once you can go back and change your vote secretly later.

**Comment by cschlom** [comment]
Hey - I think this is a great idea, and I'd love to get involved with trying to grow this. I agree with Steven Gubkin that Facebook is a super valuable resource for you - it's a good way to spread the word and helps with trust issues. 

In fact, I think that a major focus of MMC should be to encourage people to independently arrange swaps with their FB friends. (I think that this is a better idea than, for example, encouraging everybody to sign up for MMC and then trying to pair friends together, because it works independently of how many people sign up.) Since the market for votes is asymmetric (many more Hillary supporters in non-swing states than Stein supporters in swing states), it would be most effective for third party swing-state voters to reach out to friends - but of course Facebook statuses by anyone are great and raise awareness. I imagine that this sort of status would look something like: "I want to support the Green party, and don't really like either of the major candidates, but I really don't want Trump to get elected. Since I live in a swing state, I'd like to swap my PA Stein vote for a Clinton vote in a non-swing state. Message me if you or a friend would be interested! [link to article or FAQ page from MMC which explains more about the rationale/procedure for vote swapping]"

I think it would also be worthwhile to contact/learn from similar organizations. Votepair (http://oxhouse.org/politics/votepair.org/) did this in 2004; R4C16 (the organization featured in this NYT opinion piece: http://www.nytimes.com/2016/09/16/opinion/anti-trump-republicans-dont-waste-your-vote-trade-it.html?smid=pl-share) appears to be doing something similar now. Balanced Rebellion does something fairly different but ran a viral-ish targeted Facebook ad campaign - this could be an effective tactic for you.

A couple nit-picky things about your FAQ page, which I bring up since I'd like something like this page to be more front-and-center if you end up pushing for independent pairing:
- The "Why wait till October" question is outdated, since it is October now
- The "is this legal" question links to a Wikipedia page whose first words are, "In the United States, the legality of vote pairing in public elections has been questioned." This is fine, and I certainly don't want to mislead people, but you could link to the opinion in the case you mention, http://cdn.ca9.uscourts.gov/datastore/opinions/2007/08/06/0655517.pdf.
- I like your answer to the trust question, but if you do encourage people to pair with Facebook friends, that could be mentioned here. Also - and this is kind of a technical point, so I don't think you need to include it, I just wanted to mention it - you don't need 100% trust for vote swapping to make sense. If you think your partner is only 50% likely to go through with the swap, it can still make sense for you to pair with them. Scott Aaronson makes this point in his HuffPost interview, I think.

And one final point: what is a swing state and what isn't? I think pretty much the only thing that matters in determining the answer is the 538 voter power index (it's on the right; you have to scroll down a bit): http://projects.fivethirtyeight.com/2016-election-forecast/?ex_cid=rrpromo. In particular, by this metric Texas is not a swing state, although R4C16 apparently believes it is.

**Comment by sdhull** [comment]
@cschlom good suggestions, I'll update the FAQ as you suggest.

As for what is a swing state and what is not -- I thought it would be easier to figure out. I spent much of Saturday examining data & different news outlets' lists of swing states. A core group of states was always present, but the edges of the groups were a bit different depending on which news outlet you're looking at.

I decided to go with [data from Princeton](http://election.princeton.edu/state-by-state-probabilities/). See my slightly modified version of their csv [here](https://github.com/sdhull/strategic_voting/blob/master/lib/assets/ev_stateprobs.csv). Then you can check out my (arguably somewhat arbitrary) definition of `State#swing_state?` [in the State class](https://github.com/sdhull/strategic_voting/blob/master/app/models/state.rb#L19). The Princeton data has columns `win probability adding 2% to Democratic nominee` and `win probability adding 2% to Republican nominee` which I renamed to `optimistic_win_p` and `pessimistic_win_p` (respectively). Idea is that if these vary significantly (arbitrary cutoff of 10), then it's a swing state. I'm pretty satisfied with the resulting list.

Honestly we don't have nearly enough registrations currently to affect the election so I'm not too worried about really nailing this stuff. I'm doing this in my spare time and frankly there aren't enough hours in the day.

**Comment by cschlom** [comment]
Kind of exciting times for Make Mine Count - I've been tracking your Facebook shares via http://graph.facebook.com/https://www.makeminecount.org and since last night's debate you've gone from 6000 to 7000 shares. Please let me know if I can help with the growth process in any way.

**Comment by sdhull** [comment]
Wow that's cool @cschlom I didn't realize it was possible to track shares across FB that way! Thanks!

If you have any contacts in press, I think a mainstream press hit would really do the trick. Otherwise, I think just resharing every once in awhile is probably a good idea. People need to see something a few times before they go check it out or decide to sign up sometimes. It's like getting used to water in a cool pool or something 😉

**Comment by cschlom** [comment]
I think you guys should run Facebook ads, targeted (for example) at people in swing states who like Bernie Sanders's page. Balanced Rebellion used a viral FB ad (they also encourage visitors to their website to donate in order to buy more ad space) to get 700K FB shares (MMC is at 11K and it's tapered off). 

I'd be happy to put up some $$ for ads and/or to handle the whole operation. I don't think we need anything flashy, just something informative and a link - maybe like http://imgur.com/a/NOPSi. Let me know if this would be of interest!

**Comment by sdhull** [comment]
http://imgur.com/a/NOPSi -- this is brilliant. I think it'd be fantastic if you wanted to spearhead this. Let me know if you need me to set up a FB pixel, I've done it a couple other times for other people who've run FB ads. The other ads have finished though, so I can safely replace the current pixel with yours.

**Comment by cschlom** [comment]
Hmm were these other ads for Make Mine Count? If so, it might be useful for me to have some info about them (who was targeted, how many ads, effectiveness).

**Comment by sdhull** [comment]
Yeah they were. DM me on [twitter](https://twitter.com/producerSteve) (you might have to follow me first).

**Comment by cschlom** [comment]
Followed you (cschlom on Twitter); looks like you have to follow me back for me to DM you. Alternatively you could just email me any info you have on previous ad campaigns and/or contact info of the people who ran them. My email is my GitHub user name at gmail.
